/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HouseRouteImport } from './routes/_house'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PlayRouteImport } from './routes/play'
import { Route as HouseIndexRouteImport } from './routes/_house/index'
import { Route as HouseAnimeRouteImport } from './routes/_house/anime'
import { Route as HouseAudioRouteImport } from './routes/_house/audio'
import { Route as HouseComicsRouteImport } from './routes/_house/comics'
import { Route as HouseLoreRouteImport } from './routes/_house/lore'
import { Route as HouseReadRouteImport } from './routes/_house/read'
import { Route as HouseSubscribeRouteImport } from './routes/_house/subscribe'
import { Route as ApiRtcRouteImport } from './routes/api/rtc'
import { Route as HouseAnimeIdRouteImport } from './routes/_house/anime.$id'
import { Route as HouseAudioIdRouteImport } from './routes/_house/audio.$id'
import { Route as HouseComicsIdRouteImport } from './routes/_house/comics.$id'
import { Route as HouseReadIndexRouteImport } from './routes/_house/read.index'
import { Route as HouseReadSlugRouteImport } from './routes/_house/read.$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const HouseRoute = HouseRouteImport.update({
  id: '/_house',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseIndexRoute = HouseIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HouseRoute,
} as any)
const HouseAnimeRoute = HouseAnimeRouteImport.update({
  id: '/anime',
  path: '/anime',
  getParentRoute: () => HouseRoute,
} as any)
const HouseAudioRoute = HouseAudioRouteImport.update({
  id: '/audio',
  path: '/audio',
  getParentRoute: () => HouseRoute,
} as any)
const HouseComicsRoute = HouseComicsRouteImport.update({
  id: '/comics',
  path: '/comics',
  getParentRoute: () => HouseRoute,
} as any)
const HouseLoreRoute = HouseLoreRouteImport.update({
  id: '/lore',
  path: '/lore',
  getParentRoute: () => HouseRoute,
} as any)
const HouseReadRoute = HouseReadRouteImport.update({
  id: '/read',
  path: '/read',
  getParentRoute: () => HouseRoute,
} as any)
const HouseSubscribeRoute = HouseSubscribeRouteImport.update({
  id: '/subscribe',
  path: '/subscribe',
  getParentRoute: () => HouseRoute,
} as any)
const ApiRtcRoute = ApiRtcRouteImport.update({
  id: '/api/rtc',
  path: '/api/rtc',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseAnimeIdRoute = HouseAnimeIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => HouseAnimeRoute,
} as any)
const HouseAudioIdRoute = HouseAudioIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => HouseAudioRoute,
} as any)
const HouseComicsIdRoute = HouseComicsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => HouseComicsRoute,
} as any)
const HouseReadIndexRoute = HouseReadIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HouseReadRoute,
} as any)
const HouseReadSlugRoute = HouseReadSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => HouseReadRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof HouseIndexRoute
  '/login': typeof LoginRoute
  '/play': typeof PlayRoute
  '/anime': typeof HouseAnimeRouteWithChildren
  '/audio': typeof HouseAudioRouteWithChildren
  '/comics': typeof HouseComicsRouteWithChildren
  '/lore': typeof HouseLoreRoute
  '/read': typeof HouseReadRouteWithChildren
  '/subscribe': typeof HouseSubscribeRoute
  '/api/rtc': typeof ApiRtcRoute
  '/anime/$id': typeof HouseAnimeIdRoute
  '/audio/$id': typeof HouseAudioIdRoute
  '/comics/$id': typeof HouseComicsIdRoute
  '/read/$slug': typeof HouseReadSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/read/': typeof HouseReadIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/play': typeof PlayRoute
  '/anime': typeof HouseAnimeRouteWithChildren
  '/audio': typeof HouseAudioRouteWithChildren
  '/comics': typeof HouseComicsRouteWithChildren
  '/lore': typeof HouseLoreRoute
  '/subscribe': typeof HouseSubscribeRoute
  '/api/rtc': typeof ApiRtcRoute
  '/': typeof HouseIndexRoute
  '/anime/$id': typeof HouseAnimeIdRoute
  '/audio/$id': typeof HouseAudioIdRoute
  '/comics/$id': typeof HouseComicsIdRoute
  '/read/$slug': typeof HouseReadSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/read': typeof HouseReadIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_house': typeof HouseRouteWithChildren
  '/login': typeof LoginRoute
  '/play': typeof PlayRoute
  '/_house/anime': typeof HouseAnimeRouteWithChildren
  '/_house/audio': typeof HouseAudioRouteWithChildren
  '/_house/comics': typeof HouseComicsRouteWithChildren
  '/_house/lore': typeof HouseLoreRoute
  '/_house/read': typeof HouseReadRouteWithChildren
  '/_house/subscribe': typeof HouseSubscribeRoute
  '/api/rtc': typeof ApiRtcRoute
  '/_house/': typeof HouseIndexRoute
  '/_house/anime/$id': typeof HouseAnimeIdRoute
  '/_house/audio/$id': typeof HouseAudioIdRoute
  '/_house/comics/$id': typeof HouseComicsIdRoute
  '/_house/read/$slug': typeof HouseReadSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_house/read/': typeof HouseReadIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/play'
    | '/anime'
    | '/audio'
    | '/comics'
    | '/lore'
    | '/read'
    | '/subscribe'
    | '/api/rtc'
    | '/anime/$id'
    | '/audio/$id'
    | '/comics/$id'
    | '/read/$slug'
    | '/api/auth/$'
    | '/read/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/play'
    | '/anime'
    | '/audio'
    | '/comics'
    | '/lore'
    | '/subscribe'
    | '/api/rtc'
    | '/'
    | '/anime/$id'
    | '/audio/$id'
    | '/comics/$id'
    | '/read/$slug'
    | '/api/auth/$'
    | '/read'
  id:
    | '__root__'
    | '/_house'
    | '/login'
    | '/play'
    | '/_house/anime'
    | '/_house/audio'
    | '/_house/comics'
    | '/_house/lore'
    | '/_house/read'
    | '/_house/subscribe'
    | '/api/rtc'
    | '/_house/'
    | '/_house/anime/$id'
    | '/_house/audio/$id'
    | '/_house/comics/$id'
    | '/_house/read/$slug'
    | '/api/auth/$'
    | '/_house/read/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  HouseRoute: typeof HouseRouteWithChildren
  LoginRoute: typeof LoginRoute
  PlayRoute: typeof PlayRoute
  ApiRtcRoute: typeof ApiRtcRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_house': {
      id: '/_house'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof HouseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_house/': {
      id: '/_house/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof HouseIndexRouteImport
      parentRoute: typeof HouseRoute
    }
    '/_house/anime': {
      id: '/_house/anime'
      path: '/anime'
      fullPath: '/anime'
      preLoaderRoute: typeof HouseAnimeRouteImport
      parentRoute: typeof HouseRoute
    }
    '/_house/audio': {
      id: '/_house/audio'
      path: '/audio'
      fullPath: '/audio'
      preLoaderRoute: typeof HouseAudioRouteImport
      parentRoute: typeof HouseRoute
    }
    '/_house/comics': {
      id: '/_house/comics'
      path: '/comics'
      fullPath: '/comics'
      preLoaderRoute: typeof HouseComicsRouteImport
      parentRoute: typeof HouseRoute
    }
    '/_house/lore': {
      id: '/_house/lore'
      path: '/lore'
      fullPath: '/lore'
      preLoaderRoute: typeof HouseLoreRouteImport
      parentRoute: typeof HouseRoute
    }
    '/_house/read': {
      id: '/_house/read'
      path: '/read'
      fullPath: '/read'
      preLoaderRoute: typeof HouseReadRouteImport
      parentRoute: typeof HouseRoute
    }
    '/_house/subscribe': {
      id: '/_house/subscribe'
      path: '/subscribe'
      fullPath: '/subscribe'
      preLoaderRoute: typeof HouseSubscribeRouteImport
      parentRoute: typeof HouseRoute
    }
    '/api/rtc': {
      id: '/api/rtc'
      path: '/api/rtc'
      fullPath: '/api/rtc'
      preLoaderRoute: typeof ApiRtcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_house/anime/$id': {
      id: '/_house/anime/$id'
      path: '/$id'
      fullPath: '/anime/$id'
      preLoaderRoute: typeof HouseAnimeIdRouteImport
      parentRoute: typeof HouseAnimeRoute
    }
    '/_house/audio/$id': {
      id: '/_house/audio/$id'
      path: '/$id'
      fullPath: '/audio/$id'
      preLoaderRoute: typeof HouseAudioIdRouteImport
      parentRoute: typeof HouseAudioRoute
    }
    '/_house/comics/$id': {
      id: '/_house/comics/$id'
      path: '/$id'
      fullPath: '/comics/$id'
      preLoaderRoute: typeof HouseComicsIdRouteImport
      parentRoute: typeof HouseComicsRoute
    }
    '/_house/read/': {
      id: '/_house/read/'
      path: '/'
      fullPath: '/read/'
      preLoaderRoute: typeof HouseReadIndexRouteImport
      parentRoute: typeof HouseReadRoute
    }
    '/_house/read/$slug': {
      id: '/_house/read/$slug'
      path: '/$slug'
      fullPath: '/read/$slug'
      preLoaderRoute: typeof HouseReadSlugRouteImport
      parentRoute: typeof HouseReadRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface HouseAnimeRouteChildren {
  HouseAnimeIdRoute: typeof HouseAnimeIdRoute
}

const HouseAnimeRouteChildren: HouseAnimeRouteChildren = {
  HouseAnimeIdRoute: HouseAnimeIdRoute,
}

const HouseAnimeRouteWithChildren = HouseAnimeRoute._addFileChildren(
  HouseAnimeRouteChildren,
)

interface HouseAudioRouteChildren {
  HouseAudioIdRoute: typeof HouseAudioIdRoute
}

const HouseAudioRouteChildren: HouseAudioRouteChildren = {
  HouseAudioIdRoute: HouseAudioIdRoute,
}

const HouseAudioRouteWithChildren = HouseAudioRoute._addFileChildren(
  HouseAudioRouteChildren,
)

interface HouseComicsRouteChildren {
  HouseComicsIdRoute: typeof HouseComicsIdRoute
}

const HouseComicsRouteChildren: HouseComicsRouteChildren = {
  HouseComicsIdRoute: HouseComicsIdRoute,
}

const HouseComicsRouteWithChildren = HouseComicsRoute._addFileChildren(
  HouseComicsRouteChildren,
)

interface HouseReadRouteChildren {
  HouseReadSlugRoute: typeof HouseReadSlugRoute
  HouseReadIndexRoute: typeof HouseReadIndexRoute
}

const HouseReadRouteChildren: HouseReadRouteChildren = {
  HouseReadSlugRoute: HouseReadSlugRoute,
  HouseReadIndexRoute: HouseReadIndexRoute,
}

const HouseReadRouteWithChildren = HouseReadRoute._addFileChildren(
  HouseReadRouteChildren,
)

interface HouseRouteChildren {
  HouseAnimeRoute: typeof HouseAnimeRouteWithChildren
  HouseAudioRoute: typeof HouseAudioRouteWithChildren
  HouseComicsRoute: typeof HouseComicsRouteWithChildren
  HouseLoreRoute: typeof HouseLoreRoute
  HouseReadRoute: typeof HouseReadRouteWithChildren
  HouseSubscribeRoute: typeof HouseSubscribeRoute
  HouseIndexRoute: typeof HouseIndexRoute
}

const HouseRouteChildren: HouseRouteChildren = {
  HouseAnimeRoute: HouseAnimeRouteWithChildren,
  HouseAudioRoute: HouseAudioRouteWithChildren,
  HouseComicsRoute: HouseComicsRouteWithChildren,
  HouseLoreRoute: HouseLoreRoute,
  HouseReadRoute: HouseReadRouteWithChildren,
  HouseSubscribeRoute: HouseSubscribeRoute,
  HouseIndexRoute: HouseIndexRoute,
}

const HouseRouteWithChildren = HouseRoute._addFileChildren(HouseRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  HouseRoute: HouseRouteWithChildren,
  LoginRoute: LoginRoute,
  PlayRoute: PlayRoute,
  ApiRtcRoute: ApiRtcRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
